os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
install:
- git submodule update --init --recursive
before_build:
- nuget restore
build:
  project: MineLib.Android.sln
  verbosity: minimal
